[package]
name = "dlc-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.7", optional = true }
bitcoin = { version = "0.29.2", features = ["serde"] }
dlc = { version = "0.4.0", features = ["serde"] }
dlc-manager = { version = "0.4.0", features = ["serde"] }
dlc-messages = { version = "0.4.0", features = ["serde"] }
dlc-trie = { version = "0.4.0", features = ["use-serde"] }
hex = "0.4.3"
lightning = "0.0.116"
log = "0.4.14"
rand_chacha = { version = "0.3.1", optional = true }
secp256k1-zkp = { version = "0.7.0", features = [
    "bitcoin_hashes",
    "rand",
    "rand-std",
    "use-serde",
] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
thiserror = "1.0.44"
serde_bytes = "0.11.12"

[dev-dependencies]
wasm-bindgen-test = "0.3.34"
bitcoincore-rpc = { version = "0.16.0" }
bitcoincore-rpc-json = { version = "0.16.0" }
criterion = "0.4.0"
env_logger = "0.9.1"
secp256k1-zkp = { version = "0.7.0", features = [
    "bitcoin_hashes",
    "rand",
    "rand-std",
    "global-context",
    "use-serde",
] }
serde = "1.0"
serde_json = "1.0"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
lto = true
